### ISSUE TITLE
docker web doesn't build

### ISSUE THREAD

**Issue by dakotabenjamin** [developmentseed/osm-seed#199]
I tried rebasing the recent changs on develop to `hotosm-osmseed` but I am running into an issue building the web container. I get the same error when trying to build from develop directly. 

```
Step 57/71 : RUN bundle exec rake i18n:js:export
 ---> Running in 7816001ea176
ESC[91m/var/www/config/initializers/config.rb:19: warning: already initialized constant ALLOWED_STATU
S
ESC[0mESC[91m/var/www/config/initializers/config.rb:19: warning: previous definition of ALLOWED_STATU
S was here
ESC[0mESC[91mrake aborted!
ESC[0mESC[91mSyntaxError: /var/www/config/initializers/oauth.rb:55: syntax error, unexpected ..., exp
ecting ')'
...     def self.before_filter(...)
...                            ^~~
/var/www/config/initializers/oauth.rb:59: syntax error, unexpected ..., expecting ')'
...def self.skip_before_filter(...)
...                            ^~~
/var/www/config/initializers/oauth.rb:90: syntax error, unexpected end-of-input, expecting end
ESC[0mESC[91m/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.
rb:59:in `load'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:326:in `block in load'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:326:in `load'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/engine.rb:681:in `block in load_config_initializer'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:205:in `instrument'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/engine.rb:680:in `load_config_initializer'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/engine.rb:633:in `each'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/engine.rb:633:in `block in <class:Engine>'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `each'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
/var/www/config/environment.rb:5:in `<main>'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/.gem/ruby/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/var/.gem/ruby/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/application.rb:360:in `require_environment!'
/var/.gem/ruby/gems/railties-6.1.3.2/lib/rails/application.rb:526:in `block in run_tasks_blocks'
/var/.gem/ruby/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
/var/.gem/ruby/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
/var/.gem/ruby/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/var/.gem/ruby/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
/usr/local/bin//bundle:23:in `load'
/usr/local/bin//bundle:23:in `<main>'
ESC[0mESC[91mTasks: TOP => i18n:js:export => environment
ESC[0mESC[91m(See full trace by running task with --trace)
ESC[0m
```

I tried a few different commits of openstreetmap-website but either got errors that ruby packages had been removed (too old, i presume) or the same error. I thought it might be related to the new Oauth 2.0 changes on the website- however i still get the same error when pulling a commit prior to that merge. 

Any insights here would be appreciated.

**Comment by batpad** [comment]
@Rub21 would you have any time to look into this?

**Comment by dakotabenjamin** [comment]
This may be due to the ruby version- openstreetmap-website requires v2.7+ and the dockerfile installs 2.6.6

**Comment by Rub21** [comment]
@dakotabenjamin Sorry for the delay, the issue has been fixed  at https://github.com/developmentseed/osm-seed/pull/202#partial-pull-merging
