### ISSUE TITLE
Web container issue in kubernetes 

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#226]
Testing out lates openstreetmap software(https://github.com/developmentseed/osm-seed/pull/225) in docker-compose works fine , but in kubernetes does not work 
```
Waiting to start rails ports server...
Waiting to start rails ports server...
rails aborted!
Config::Validation::Error: Config validation failed:

  avatar_storage: is missing
  trace_file_storage: is missing
  trace_image_storage: is missing
  trace_icon_storage: is missing
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/validation/validate.rb:20:in `validate_using!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/validation/validate.rb:8:in `validate!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/options.rb:58:in `reload!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config.rb:48:in `load_files'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config.rb:56:in `load_and_set_settings'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/integrations/rails/railtie.rb:11:in `preload'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/railtie.rb:207:in `public_send'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/railtie.rb:207:in `method_missing'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:96:in `inherited'
/var/www/config/application.rb:23:in `<module:OpenStreetMap>'
/var/www/config/application.rb:21:in `<main>'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
/var/www/Rakefile:4:in `<main>'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/command.rb:50:in `invoke'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/commands.rb:18:in `<main>'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/var/lib/gems/2.7.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
Waiting to start rails ports server...
rake aborted!
Config::Validation::Error: Config validation failed:

  avatar_storage: is missing
  trace_file_storage: is missing
  trace_image_storage: is missing
  trace_icon_storage: is missing
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/validation/validate.rb:20:in `validate_using!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/validation/validate.rb:8:in `validate!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/options.rb:58:in `reload!'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config.rb:48:in `load_files'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config.rb:56:in `load_and_set_settings'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/integrations/rails/railtie.rb:11:in `preload'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/railtie.rb:207:in `public_send'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/railtie.rb:207:in `method_missing'
/var/lib/gems/2.7.0/gems/config-3.1.1/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
/var/lib/gems/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/var/lib/gems/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:96:in `inherited'
/var/www/config/application.rb:23:in `<module:OpenStreetMap>'
/var/www/config/application.rb:21:in `<top (required)>'
/var/www/Rakefile:4:in `require_relative'
/var/www/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by Rub21** [comment]
The issue was because some latest changes on osm-websites,  I fixed that.
