### ISSUE TITLE
Error building OSM api website 

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#304]
```sh
#14 [10/40] RUN mv openstreetmap-website-c24b5481812aba9e83da1fd855ccb37f92c5d75e/* /var/www/
#14 DONE 0.2s

#15 [11/40] WORKDIR /var/www
#15 DONE 0.0s

#16 [12/40] RUN echo "gem 'image_optim_pack', :git => 'https://github.com/toy/image_optim_pack.git'" >> Gemfile
#16 DONE 0.2s

#17 [13/40] RUN gem install bundler && bundle install
#17 13.28 ERROR:  Error installing bundler:
#17 13.28 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
#17 13.28 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.0.0.
#17 ERROR: process "/bin/sh -c gem install bundler && bundle install" did not complete successfully: exit code: 1
------
 > [13/40] RUN gem install bundler && bundle install:
13.28 ERROR:  Error installing bundler:
13.28 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
13.28 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.0.0.
------
Dockerfile:51
--------------------
  49 |     
  50 |     # Install Ruby packages
  51 | >>> RUN gem install bundler && bundle install
  52 |     
  53 |     # Configure database.yml and secrets.yml
--------------------
ERROR: failed to solve: process "/bin/sh -c gem install bundler && bundle install" did not complete successfully: exit code: 1
Updating osm-seed/Chart.yaml: version: 0.1.0-n772.h1c74419
$> docker build -t developmentseed/osmseed-web:0.1.0-n772.h1c74419 images/web -f images/web/Dockerfile
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.15/x64/bin/chartpress", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/chartpress.py", line 1034, in main
    platforms=args.platform,
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/chartpress.py", line 610, in build_images
    platforms=platforms,
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/chartpress.py", line 359, in build_image
    _check_call(cmd)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/chartpress.py", line 69, in _check_call
    return _run_cmd(subprocess.check_call, cmd, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/chartpress.py", line 64, in _run_cmd
    return call(cmd, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'developmentseed/osmseed-web:0.1.0-n772.h1c74419', 'images/web', '-f', 'images/web/Dockerfile']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

cc. @batpad

**Comment by Rub21** [comment]
this issue was fixed. closing the ticket
